apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: curator-deployments
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Atemndobs/curator-deployments.git
    targetRevision: HEAD
    path: argocd
    helm:
      releaseName: sealed-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: curator
  syncPolicy:
    automated:
      prune: false
      selfHeal: true