apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: curator-deployments
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Atemndobs/curator-deployments
    targetRevision: HEAD
    helm:
      releaseName: sealed-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeseal